version: "3.8"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
      args: [ "NODE_ENV=development" ]
    env_file: .env

networks:
  default:
    external:
      name: magehand